---
name: Generate
on:
  repository_dispatch:
    types: [generate]
env:
  GH_TOKEN: ${{ secrets.NUON_BOT_GITHUB_TOKEN }}
  VERSION: ${{ github.event.client_payload.version }}
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable commit signing
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.NUON_BOT_PRIVATE_KEY }}
          passphrase: ${{ secrets.NUON_BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Save version
        run: |
          echo $VERSION > version.txt
      - name: Generate
        run: |
          ./scripts/generate.sh $VERSION
      - name: Commit changes
        run: |
          git checkout -b nuonbot/generate-$VERSION
          git add .
          git commit -m "ci: generate formula for CLI version $VERSION"
          git push -u origin nuonbot/generate-$VERSION
      - name: Open PR
        run: |
          gh pr create --title "ci: generate formula for CLI version $VERSION" --body "ci: generate formula for CLI version $VERSION" --label "auto-merge"
